=== chrimaeon/gradle-licenses-plugin/src/main/schema/licenses-schema.json
{
  "$id": "https://www.cmgapps.com/schema/licenses-schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Licenses",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "mavenCoordinates": {
        "type": "object",
        "$ref": "#/$defs/MavenCoordinates"
      },
      "name": {
        "type": [
          "string",
          "null"
        ]
      },
      "description": {
        "type": [
          "string",
          "null"
        ]
      },
      "licenses": {
        "type": "array",
        "items": {
          "type": "object",
          "$ref": "#/$defs/License"
        }
      },
      "additionalProperties": false
    },
    "required": [
      "mavenCoordinates",
      "name",
      "description",
      "licenses"
    ],
    "additionalProperties": false
  },
  "$defs": {
    "MavenCoordinates": {
      "properties": {
        "groupId": {
          "type": "string"
        },
        "artifactId": {
          "type": "string"
        },
        "version": {
          "type": "string"
        }
      },
      "required": [
        "groupId",
        "artifactId",
        "version"
      ],
      "additionalProperties": false
    },
    "License": {
      "properties": {
        "spdxLicenseIdentifier": {
          "type": [
            "string",
            "null"
          ]
        },
        "name": {
          "type": "string"
        },
        "url": {
          "type": "string"
        }
      },
      "required": [
        "spdxLicenseIdentifier",
        "name",
        "url"
      ],
      "additionalProperties": false
    }
  }
}

=== chrimaeon/gradle-licenses-plugin/src/functionalTest/fixtures/java-library-handle-complete-dsl/expected/build/reports/licenses/licenseReport/licenses.json
[
    {
        "mavenCoordinates": {
            "groupId": "group",
            "artifactId": "name",
            "version": "1.0.0"
        },
        "name": "Fake dependency name",
        "description": "Fake dependency description",
        "licenses": [
            {
                "spdxLicenseIdentifier": null,
                "name": "Some license",
                "url": "http://website.tld/"
            }
        ]
    }
]

=== chrimaeon/gradle-licenses-plugin/src/functionalTest/fixtures/android-gradle-plugin-9/expected/licenseDebugReport/build/reports/licenses/licenseDebugReport/licenses.json
[
    {
        "mavenCoordinates": {
            "groupId": "com.squareup.retrofit2",
            "artifactId": "retrofit",
            "version": "2.3.0"
        },
        "name": "Retrofit",
        "description": null,
        "licenses": [
            {
                "spdxLicenseIdentifier": "Apache-2.0",
                "name": "Apache License 2.0",
                "url": "https://spdx.org/licenses/Apache-2.0.html"
            }
        ]
    }
]

=== chrimaeon/gradle-licenses-plugin/src/functionalTest/fixtures/android-gradle-plugin-9/expected/build/reports/licenses/licenseDebugReport/licenses.json
[
    {
        "mavenCoordinates": {
            "groupId": "com.squareup.retrofit2",
            "artifactId": "retrofit",
            "version": "2.3.0"
        },
        "name": "Retrofit",
        "description": null,
        "licenses": [
            {
                "spdxLicenseIdentifier": "Apache-2.0",
                "name": "Apache 2.0",
                "url": "http://www.apache.org/licenses/LICENSE-2.0.txt"
            }
        ]
    }
]
